### PR TITLE
added sandbox for testing

### PR DESCRIPTION
**Pull request by xonoxitron**

### CODE REVIEW

**Comment by mrdoob** [comment]
Hmm, the rotation seems a bit weird here:
https://rawgit.com/xonoxitron/daydream-controller.js/master/sandbox/index.html

**Comment by xonoxitron** [comment]
I know.
The decoding stuff you used has problems.

**Comment by mrdoob** [comment]
Was working on adding a viewer too. My approach has a bit of less overhead (no a-frame layer and no objloader, only three.js). https://github.com/mrdoob/daydream-controller.js/commit/0e3f9cba32606c4dedc4b1c86edf7a0cfba06c10

**Comment by xonoxitron** [comment]
Cool.
Curious to see your improvements about the orientation

**Comment by mrdoob** [comment]
Ended up using Madgwick too. https://github.com/mrdoob/daydream-controller.js/commit/5069b88c945b4386d5b055015c1c270245ff5c9b

**Pull request closed without merging**
